version: 2
jobs:
  build:
    environment:
      ECR_REPOSITORY: 308882746353.dkr.ecr.us-east-1.amazonaws.com/parkassist/sonatype-nexus
      REGISTRY_ID: "308882746353"
    docker:
    - image: docker:17.09.0-ce-git
    working_directory: /sonatype-nexus
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup ECR Login
          command: |
            apk add --no-cache py-pip
            pip install awscli
            eval $(aws ecr get-login --no-include-email --registry-ids ${REGISTRY_ID})
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/sonatype-nexus.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=${ECR_REPOSITORY}:latest -t ${ECR_REPOSITORY}:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/sonatype-nexus.tar ${ECR_REPOSITORY}:latest
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/sonatype-nexus.tar
      - deploy:
          name: Push to ECR
          command: |
            docker tag "${ECR_REPOSITORY}:latest" "${ECR_REPOSITORY}:${CIRCLE_SHA1}"
            docker push "${ECR_REPOSITORY}:${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/