statefulset:
  enabled: true
replicaCount: 1
nexus:
  imageName: 308882746353.dkr.ecr.us-east-1.amazonaws.com/parkassist/sonatype-nexus
  nodeSelector:
    dedicated: ondemand
  resources:
    limits:
      cpu: 750m
      memory: 2000Mi
    requests:
      cpu: 750m
      memory: 2000Mi
nexusProxy:
  enabled: false
persistence:
  storageClass: gp2
  pdName: nexus-data-disk
  fsType: ext4
ingress:
  tls:
    enabled: false
  labels:
    dns: route53
  annotations:
    domainName: nexus.pastaging.net
  rules:
    - host: nexus.pastaging.net
      http:
        paths:
          - path: /
            backend:
              serviceName: sonatype-nexus-lb
              servicePort: http
serviceAccount:
  create: false
service:
  enabled: true
  type: ClusterIP
  name: sonatype-nexus-lb
  ports:
  - name: http
    port: 8081
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "ondemand"
    effect: "NoSchedule"